//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFood.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookMyFood.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to connect..
        /// </summary>
        public static string Anerroroccuredwhiletryingtoconnect {
            get {
                return ResourceManager.GetString("Anerroroccuredwhiletryingtoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my order.
        /// </summary>
        public static string Changemyorder {
            get {
                return ResourceManager.GetString("Changemyorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common error.
        /// </summary>
        public static string Commonerror {
            get {
                return ResourceManager.GetString("Commonerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to .
        /// </summary>
        public static string Connectedto {
            get {
                return ResourceManager.GetString("Connectedto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPY THIS.
        /// </summary>
        public static string COPYTHIS {
            get {
                return ResourceManager.GetString("COPYTHIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and Programmed by.
        /// </summary>
        public static string DesignedandProgrammedby {
            get {
                return ResourceManager.GetString("DesignedandProgrammedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit parameters.
        /// </summary>
        public static string EditingModeRadioButtonLabel {
            get {
                return ResourceManager.GetString("EditingModeRadioButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error appeared when you&apos;ve tried to send user data. Try again..
        /// </summary>
        public static string ErrorappearedwhenyouvetriedtosenduserdataTryagain {
            get {
                return ResourceManager.GetString("ErrorappearedwhenyouvetriedtosenduserdataTryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while stop trying:.
        /// </summary>
        public static string Errorwhilestoptrying {
            get {
                return ResourceManager.GetString("Errorwhilestoptrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string ExpanderLabel {
            get {
                return ResourceManager.GetString("ExpanderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found working Windows Firewall Service. Would you like to stop it?.
        /// </summary>
        public static string FoundworkingWindowsFirewallServiceWouldyouliketostopit {
            get {
                return ResourceManager.GetString("FoundworkingWindowsFirewallServiceWouldyouliketostopit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient rights to launch a server..
        /// </summary>
        public static string Insufficientrightstolaunchaserver {
            get {
                return ResourceManager.GetString("Insufficientrightstolaunchaserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient rights to stop the service..
        /// </summary>
        public static string Insufficientrightstostoptheservice {
            get {
                return ResourceManager.GetString("Insufficientrightstostoptheservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is called:.
        /// </summary>
        public static string Itiscalled {
            get {
                return ResourceManager.GetString("Itiscalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempahan.
        /// </summary>
        public static string JoiningModeRadioButtonLabel {
            get {
                return ResourceManager.GetString("JoiningModeRadioButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageFieldLabel {
            get {
                return ResourceManager.GetString("LanguageFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader comp. or IP.
        /// </summary>
        public static string LeaderAddressFieldLabel {
            get {
                return ResourceManager.GetString("LeaderAddressFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to book.
        /// </summary>
        public static string LeadModeRadioButtonLabel {
            get {
                return ResourceManager.GetString("LeadModeRadioButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My order is done.
        /// </summary>
        public static string Myorderisdone {
            get {
                return ResourceManager.GetString("Myorderisdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myself.
        /// </summary>
        public static string Myself {
            get {
                return ResourceManager.GetString("Myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Domain Name.
        /// </summary>
        public static string NoDomainName {
            get {
                return ResourceManager.GetString("NoDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all users are ready to calculate their orders. Continue forcibly?.
        /// </summary>
        public static string NotallusersarereadytocalculatetheirordersContinueforcibly {
            get {
                return ResourceManager.GetString("NotallusersarereadytocalculatetheirordersContinueforcibly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  out of .
        /// </summary>
        public static string outof {
            get {
                return ResourceManager.GetString("outof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants readiness: .
        /// </summary>
        public static string Participantsreadiness {
            get {
                return ResourceManager.GetString("Participantsreadiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a deliverer.
        /// </summary>
        public static string Pickadeliverer {
            get {
                return ResourceManager.GetString("Pickadeliverer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICK YOUR ORDER POSITIONS.
        /// </summary>
        public static string PICKORDERPOSITIONS {
            get {
                return ResourceManager.GetString("PICKORDERPOSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port (opt.).
        /// </summary>
        public static string PortFieldLabel {
            get {
                return ResourceManager.GetString("PortFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status : An orders were calculated.
        /// </summary>
        public static string ServerStatusAnorderswerecalculated {
            get {
                return ResourceManager.GetString("ServerStatusAnorderswerecalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status : Gathering participants readiness info.
        /// </summary>
        public static string ServerStatusGatheringparticipantsreadinessinfo {
            get {
                return ResourceManager.GetString("ServerStatusGatheringparticipantsreadinessinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status : Picking an items to order.
        /// </summary>
        public static string ServerStatusPickinganitemstoorder {
            get {
                return ResourceManager.GetString("ServerStatusPickinganitemstoorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status : Selecting Store.
        /// </summary>
        public static string ServerStatusSelectingStore {
            get {
                return ResourceManager.GetString("ServerStatusSelectingStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to calculate.
        /// </summary>
        public static string Starttocalculate {
            get {
                return ResourceManager.GetString("Starttocalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STORES LIST.
        /// </summary>
        public static string STORESLISTpickone {
            get {
                return ResourceManager.GetString("STORESLISTpickone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum discounted.
        /// </summary>
        public static string Sumdiscounted {
            get {
                return ResourceManager.GetString("Sumdiscounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message here.
        /// </summary>
        public static string tbChatMessageSend {
            get {
                return ResourceManager.GetString("tbChatMessageSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string tbServersListFieldLabel {
            get {
                return ResourceManager.GetString("tbServersListFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain name you have used is not available in this network..
        /// </summary>
        public static string Thedomainnameyouhaveusedisnotavailableinthisnetwork {
            get {
                return ResourceManager.GetString("Thedomainnameyouhaveusedisnotavailableinthisnetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname and port are already in use.
        /// </summary>
        public static string Thehostnameandportarealreadyinuse {
            get {
                return ResourceManager.GetString("Thehostnameandportarealreadyinuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname and port are already in use. Wait for a little..
        /// </summary>
        public static string ThehostnameandportarealreadyinuseWaitforalittle {
            get {
                return ResourceManager.GetString("ThehostnameandportarealreadyinuseWaitforalittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other users ought to look for:.
        /// </summary>
        public static string Theotherusersoughttolookfor {
            get {
                return ResourceManager.GetString("Theotherusersoughttolookfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To launch your own server you need to Run this app as Administrator..
        /// </summary>
        public static string TolaunchyourownserveryouneedtoRunthisappasAdministrator {
            get {
                return ResourceManager.GetString("TolaunchyourownserveryouneedtoRunthisappasAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stop the  Windows Firewall Service you must Run this app as Administrator..
        /// </summary>
        public static string TostoptheWindowsFirewallServiceyoumustRunthisappasAdministrator {
            get {
                return ResourceManager.GetString("TostoptheWindowsFirewallServiceyoumustRunthisappasAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL SUM.
        /// </summary>
        public static string TOTALSUM {
            get {
                return ResourceManager.GetString("TOTALSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL SUM DISCOUNTED.
        /// </summary>
        public static string TOTALSUMDISCOUNTED {
            get {
                return ResourceManager.GetString("TOTALSUMDISCOUNTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to stop.
        /// </summary>
        public static string Tryingtostop {
            get {
                return ResourceManager.GetString("Tryingtostop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Leader....
        /// </summary>
        public static string WaitingforLeader {
            get {
                return ResourceManager.GetString("WaitingforLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall Service has been stopped..
        /// </summary>
        public static string WindowsFirewallServicehasbeenstopped {
            get {
                return ResourceManager.GetString("WindowsFirewallServicehasbeenstopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may encounter some problems when searching for other people&apos;s servers.
        /// </summary>
        public static string Youmayencountersomeproblemswhensearchingforotherpeoplesservers {
            get {
                return ResourceManager.GetString("Youmayencountersomeproblemswhensearchingforotherpeoplesservers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string YourNameFieldLabel {
            get {
                return ResourceManager.GetString("YourNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your server is already started..
        /// </summary>
        public static string Yourserverisalreadystarted {
            get {
                return ResourceManager.GetString("Yourserverisalreadystarted", resourceCulture);
            }
        }
    }
}
